print("Medlemskort til Katrines Kælder")
print("Medlemsnummer:\t01234567")
print("Navn:","\t\t\tLars Larsen")
print()
print("Medlemskort til","Katrines Kælder","\nMedlemsnummer:\t01234567","\nNavn:\t\t\tLars Larsen")
print()
print("Medlemskort til","Katrines Kælder","\nMedlemsnummer:\t01234567","\nNavn:\t\t\tLars Larsen")