import math
print("2 vand á 10.5 kr.\t\t\t",2*10.5,"kr.")
print("3 skåle peanuts á 5 kr.\t\t",3*5,"kr.")
print("Total\t\t\t\t\t\t",2*10.5+3*5,"kr.")
print()
# med casting
print("2 vand á 10.5 kr.\t\t\t",(int)(2*10.5),"kr.")
print("3 skåle peanuts á 5 kr.\t\t",3*5,"kr.")
print("Total\t\t\t\t\t\t",(int)(2*10.5+3*5),"kr.")
print()
print("\n*Trigonometriske funktioner*\n")
print(math.sin(math.pi))
print(math.trunc(math.sin(math.pi)))
print(math.trunc(1.7))
print(math.ceil(1.7))
print(math.sin(math.pi/2))